SOURCE_PRIVATBANK = 1
SOURCE_MONOBANK = 2
SOURCE_CHOICES = (
    (SOURCE_PRIVATBANK, 'PrivatBank'),
    (SOURCE_MONOBANK, 'MonoBank'),
)

CURRENCY_USD = 1
CURRENCY_EUR = 2
CURRENCY_CHOICES = (
    (CURRENCY_USD, 'USD'),
    (CURRENCY_EUR, 'EUR'),
)