SOURCE_PRIVATBANK = 1
SOURCE_MONOBANK = 2
SOURCE_VKURSE = 3
SOURCE_DNIPRO = 4
SOURCE_NBU = 5
SOURCE_CHOICES = (
    (SOURCE_PRIVATBANK, 'PrivatBank'),
    (SOURCE_MONOBANK, 'MonoBank'),
    (SOURCE_VKURSE, 'Vkurse'),
    (SOURCE_DNIPRO, 'Dnipro'),
    (SOURCE_NBU, 'NBU'),
)

CURRENCY_USD = 1
CURRENCY_EUR = 2
CURRENCY_CHOICES = (
    (CURRENCY_USD, 'USD'),
    (CURRENCY_EUR, 'EUR'),
)